### ISSUE TITLE
Small mistake in build.sh file

### ISSUE THREAD

**Issue by lisagsb** [open-discourse/open-discourse#119]
First a big thank you for your work! It's great to find the speeches in such a great condition to further work with them!

I noticed a small mistake in the build.sh file when building the database myself. There is a "_20" missing in the file name (05_split_xml_electoral_term_19.py) in line 27 of the build.sh file which was probably not updated after adding the 20th electoral period.

**Comment by JabobKrauskopf** [comment]
Hi! Thanks for creating the issue and bringing this to our attention!
