### ISSUE TITLE
[BUG REPORT] Fatal Error when building dataset up to term 20 Session 109

### ISSUE THREAD

**Issue by Resmond-s** [open-discourse/open-discourse#138]
**Describe the bug**
build.sh and subsequent scripts fail if they include electoral term 20 Session 109 due to missing faction/role of a speaker. Subsequent results in need of the electoral term 20 preprocessing are also missing and throw respective errors.

**To Reproduce**
1. run build.sh or alternatively just $preprocessing_path/05_split_xml_electoral_term_19_20.py
2. wait for scripts to finish
3. errors are thrown at mentioned script and later on
4. look into specific logs for errors

**Expected behavior**
build.sh should run without any errors concerning term 20.

**Desktop (please complete the following information if applicable):**
 - OS: Ubuntu
 - Version 22

**Additional context**
The error is due to missing faction/role elements of a speaker (term 20 Session 109 [20109] XML; line 3458):
```xml
<redner id="11003218">
   <name>
      <vorname>Carsten</vorname>
      <nachname>Schneider</nachname>
   </name>
</redner>
```
This throws an error due to the faction_abbrev requirements in [01_extract_speeches_and_contributions_electoral_term_19_20.py](https://github.com/open-discourse/open-discourse/blob/develop/python/src/od_lib/05_electoral_term_19_20/01_extract_speeches_and_contributions_electoral_term_19_20.py#L266). It fails to find the "fraktion" and "rolle" elements and thus exits without any further exeptions. 

**Suggested solution**
Add an further exept in [01_extract_speeches_and_contributions_electoral_term_19_20.py](https://github.com/open-discourse/open-discourse/blob/develop/python/src/od_lib/05_electoral_term_19_20/01_extract_speeches_and_contributions_electoral_term_19_20.py#L266) with position_raw = "". May cause errors further on.

**Comment by petergandenberger** [comment]
I think there are two ways to fix this issue.
1. Only catch this one bug, by adding an if-statement `if session == "20109" and first_name == 'Carsten' and last_name == 'Schneider': position_raw = ""`
2. Catching every bug like this in the future, by adding another `except` statement.

I'm happy to create the PR if we can decide on the best way :)

**Comment by JabobKrauskopf** [comment]
Hey! Sorry for the late reply.

When we were still actively maintaining the project, we wanted to fix such bugs via if-statements or similar (as you can see in the terrible code 🫠).
But since we now have little time to actively take care of all the exceptions, we also find the solution with the `except` statement suitable to keep everything running.

Feel free to create a PR! :)
