### ISSUE TITLE
Progress bar for long running processes in python scripts [FEATURE REQUEST]

### ISSUE THREAD

**Issue by insalt-glitch** [open-discourse/open-discourse#143]
**Is your feature request related to a problem? Please describe.**
The long-running python scripts just print some, quite random information in each iteration. A progress bar would make the current progress more clear. It would also be nice to switch to the python-internal [pathlib](https://docs.python.org/3/library/pathlib.html) library. Is that fine with you?

**Describe the solution you'd like**
I'd like to implement a simple progress bar to fix this.

**Additional context**
I'm currently in the process of fixing the database build pipeline. Would be nice to fix some things up.

**Comment by JabobKrauskopf** [comment]
Hey!

Thanks for the issue and the proposal! Sounds great!

> It would also be nice to switch to the python-internal pathlib library. Is that fine with you?

Sure, go ahead!

Looking forward to see your progress(-bar) :)

**Comment by insalt-glitch** [comment]
@JabobKrauskopf do you find one bigger PR? It is quite hard to separate everything.

Unfortuantely, I cannot run the last script since the database update does not work. I'm not familiar with type-script and the library you build there. Could you check it out?

I updated to node version 14 and PostgreSQL version 14 since the other docker containers are no longer supported.
