### ISSUE TITLE
[BUG REPORT] open-discourse/DOCKER_SETUP.md // docker-compose no working auth credentials 

### ISSUE THREAD

**Issue by TwistedTransistor** [open-discourse/open-discourse#50]
Hi,

I tried to use 
`docker-compose up -d` 
with the docker-compose.yml.
Straight getting the error:
`Pulling database (docker.pkg.github.com/open-discourse/open-discourse/database:latest)...
ERROR: Head https://docker.pkg.github.com/v2/open-discourse/open-discourse/database/manifests/latest: no basic auth credentials`

Going further testing the credentials on the docker.pkg.github website with the posters credentials it says:
`{"errors":[{"code":"UNAUTHORIZED","message":"Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured."}]}`

**Comment by JabobKrauskopf** [comment]
Hi @TwistedTransistor,

currently the GitHub Container Registry doesn't allow downloading public images without being logged in (https://github.community/t/docker-pull-from-public-github-package-registry-fail-with-no-basic-auth-credentials-error/16358/81)

Can you try logging into docker using your GitHub Username and   [https://github.com/settings/tokens/new](Personal Access Token) and then starting the containers via `docker-compose up -d` again?
See also: https://docs.github.com/en/free-pro-team@latest/packages/guides/configuring-docker-for-use-with-github-packages

Let me know how it went!

**Comment by TwistedTransistor** [comment]
Thx, this is the way. Everything is functioning now. Good to know that the GitHub Container Registry doesn't allow downloading public images without being logged in.

**Comment by JabobKrauskopf** [comment]
Thanks for letting me know. :) - Closing this issue now!
